version: '3.1'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8016:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./etc:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./custom_modules:/mnt/extra-addons2
  db:
    image: postgres:13
    ports:
      - 5454:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data: